# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm ci
      - echo install special library to support mongodb in memory
      - apt install libssl1.1
  build:
    commands:
      - echo Build started
      - echo Compiling the Node.js code
      - cp .env.example .env
      - cat .env
      - npm run start
  post_build:
    commands:
      - echo Build completed